### PR TITLE
fix: use ResizeObserver instead of window resize event listener

### LINKED ISSUE #33: Resize handling
Recomputing of the displayed text should happen when the size of the container element changes, and not when the window was resized.

That means, instead of handling the (window) `resize` event, a `ResizeObserver` for the element should be used.

### PR DESCRIPTION
**Pull request by obecker**
Fixes https://github.com/microlinkhq/nanoclamp/issues/33

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -93,13 +93,14 @@ const NanoClamp = ({
...
 
-    const clampLinesDebounced = debounceFn(clampLines, debounce)
-    window.addEventListener('resize', clampLinesDebounced)
-
-    return () => window.removeEventListener('resize', clampLinesDebounced)
+    if (elementRef.current != null) {
+      const observer = new ResizeObserver(debounceFn(clampLines, debounce))
+      observer.observe(elementRef.current)
+      return () => observer.disconnect()
+    }
```
Comment (breadadams) [inline src/index.ts]: **Thought**: maybe we could move `observer` to a `let` outside of this if statement, and move the return statement outside of the if? And then do something like `observe?.disconnect()`.

So we're sure we always disconnect even if the component happens to unmount. Shouldn't, but just to be on the safe side.

Comment (obecker) [reply src/index.ts]: I'm not sure if I understand your concern. Either the `observer` is created, then a cleanup function is returned that disconnects it when unmounted. Or this block is not executed (there is no observer), then no cleanup function is returned. So we are on the safe side. I guess it's more a question of readability.

Comment (obecker) [reply src/index.ts]: I've rewritten the code to use an early return. I think that way it is more clear what is happening.
(By the way, I believe we could move that early return even before the `clampLines()` call in line 97. However, I'm not sure if I miss something ...)

Comment (breadadams) [reply src/index.ts]: Sorry for the delay @obecker, the prev. code review was done from my mobile which caused me to misinterpret the code I believe 🤦.

Nevertheless, I agree that the changes you made have made it more readable. Thanks!

**Review by breadadams — APPROVED** [review]
LGTM! @Kikobeats could you take a look too?

**Comment by Kikobeats** [comment]
such a great PR; thank you for it 🙂
